<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj/editor/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);LUA_EDITING_CHECKS</DefineConstants>
    <OutputPath>bin/editor/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/LuaEditing.cs" Link="LuaEditing.cs" />
    <Compile Include="editor/EditingChecks.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
